name: Deploy Application to EB

on:
  push:
    branches:
      - main

env:
  EB_APPLICATION_NAME: 'futa.dapp'
  EB_ARTIFACTS_BUCKET: 'sampleproject-artifacts'
  APP_BUNDLE_NAME: 'futa-${{ github.sha }}.zip'
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: zip application to deploy
        run: cd ./dist && zip -r ${{ env.APP_BUNDLE_NAME }} ./

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload package to S3 bucket
        run: aws s3 cp ${{ env.APP_BUNDLE_NAME }} s3://${{env.EB_ARTIFACTS_BUCKET}}

      - name: Create EB application version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{env.EB_APPLICATION_NAME}} \
          --version-label "${{ github.sha }}" \
          --source-bundle S3Bucket="${{ env.EB_ARTIFACTS_BUCKET }}",S3Key="${{ env.APP_BUNDLE_NAME }}"

      - name: Deploy new application version
        run: |
          aws elasticbeanstalk update-environment \
          --environment-name ${{ env.EB_ENVIRONMENT_NAME }} \
          --version-label "${{ github.sha }}"
